name: 'Push to Postman'
description: 'Github action to push collections to Postman directly from your workflow
inputs:
  goal:
    description: 'Action to perform (create, update, createOrUpdate, etc..)'
    required: true
  postman-key:
    description: 'Your Postman API key'
    required: true
  postman-file:
    description: 'Postman JSON file'
    required: true
  workspace-id:
    description: 'The Postman workspace ID'
    required: false
  collection-id:
    description: 'The Postman collection ID'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
