name: Build dist 

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '**.json'
      - '**.js'
      - '**.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Install dependencies
      run: npm install
    - uses: ./
    - name: Build dist
      run: npm run build
    - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Build dist"            
